title: billow's space
email: billow.fun@gmail.com
description: 它们能做的……唯有努力地绽放光芒。让那光芒照耀着其他灯塔，也照耀着我
baseurl: ""
url: "billow.fun"
github_username: iovw
google_analytics: false
markdown: kramdown
permalink: /:year/:month/:day/:title:output_ext
# theme: minima
remote_theme: billow

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
