name: Hugo build and Publish to gh-page

on:
  push:
    branches: [ hugo ]
  pull_request:
    branches: [ hugo ]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Hugo
        run: |
          sudo apt-get update -y
          sudo apt-get install -y hugo
      - name: Hugo build
        run: |
          hugo -D
      - name: Publish to gh-page
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: master
          allow_empty_commit: false
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
