name: Ruby

on:
  push:
    branches: [jekyll]
  pull_request:
    branches: [jekyll]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build with jekyll
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle config --local build.sassc --disable-march-tune-native
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build -d dist

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: master
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
